import { ClipboardList } from 'lucide-react';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@energyiq/ui';
import { CreateOrderCard } from './create-order-card';
import { CreateOrderField, ORDER_FIELD_CLASSES } from './create-order-field';
import { ORDER_REFERENCE, SUPPLIER_OPTIONS } from './create-order-mocks';

interface CreateOrderInformationCardProps {
  supplierId: string;
  onSupplierChange: (supplierId: string) => void;
  deliveryDate: string;
  onDeliveryDateChange: (date: string) => void;
  /** Read-only reference: an auto-generated placeholder for create, the real ref for edit. */
  orderReference?: string;
}

const FIELD_CLASSES = ORDER_FIELD_CLASSES;

/** "Order Information" section: supplier (full width), then reference + date. */
export function CreateOrderInformationCard({
  supplierId,
  onSupplierChange,
  deliveryDate,
  onDeliveryDateChange,
  orderReference = ORDER_REFERENCE,
}: CreateOrderInformationCardProps) {
  return (
    <CreateOrderCard
      title="Order Information"
      subtitle="Basic order setup and scheduling"
      icon={ClipboardList}
    >
      <div className="flex flex-col gap-5">
        <CreateOrderField label="Supplier:">
          <Select value={supplierId} onValueChange={(value) => onSupplierChange(value ?? '')}>
            {/* h-14! overrides the trigger's default data-[size]:h-8. */}
            <SelectTrigger className={`${FIELD_CLASSES} h-14! dark:bg-transparent`}>
              {/* Render the supplier name, not the raw id, for the selected value. */}
              <SelectValue placeholder="Select a supplier">
                {(value) =>
                  SUPPLIER_OPTIONS.find((supplier) => supplier.id === value)?.name ??
                  'Select a supplier'
                }
              </SelectValue>
            </SelectTrigger>
            <SelectContent>
              {SUPPLIER_OPTIONS.map((supplier) => (
                <SelectItem key={supplier.id} value={supplier.id}>
                  {supplier.name}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </CreateOrderField>

        <div className="grid grid-cols-1 gap-5 sm:grid-cols-2">
          <CreateOrderField label="Order Reference:">
            {/* Auto-generated by the backend on submit. */}
            <input
              type="text"
              value={orderReference}
              readOnly
              aria-readonly="true"
              className={`${FIELD_CLASSES} cursor-not-allowed bg-[#FFFFFF0D] text-[#FFFFFFCC]`}
            />
          </CreateOrderField>

          <CreateOrderField label="Delivery Date:">
            <input
              type="date"
              value={deliveryDate}
              onChange={(event) => onDeliveryDateChange(event.target.value)}
              className={`${FIELD_CLASSES} [color-scheme:dark]`}
            />
          </CreateOrderField>
        </div>
      </div>
    </CreateOrderCard>
  );
}
