// TODO(orval): replace this whole module with the generated create-order query/mutation
// hooks once the backend lands (POST /orders, GET /products, GET /suppliers,
// GET /wallets/read for the trading balance). The shapes below mirror what those
// endpoints are expected to return so swapping them is a drop-in change.

const NGN = new Intl.NumberFormat('en-NG');

/** Formats a kobo-free naira amount as e.g. `₦620,000`. Zero renders as `₦0`. */
export function formatNaira(amount: number): string {
  return `₦${NGN.format(Math.round(amount))}`;
}

/** Gold-tier discount applied to the order subtotal. */
export const GOLD_DISCOUNT_RATE = 0.1;

// --- Suppliers ------------------------------------------------------------
// TODO(orval): replace with useGetSuppliers().
export interface CreateOrderSupplierOption {
  id: string;
  name: string;
}

export const SUPPLIER_OPTIONS: CreateOrderSupplierOption[] = [
  { id: 'rain-oil', name: 'Rain Oil Resources' },
  { id: 'total-energy', name: 'TotalEnergy Depot' },
  { id: 'ardova', name: 'Ardova Plc' },
];

export const DEFAULT_SUPPLIER_ID = 'rain-oil';

/** Auto-generated by the backend on submit; read-only placeholder until then. */
export const ORDER_REFERENCE = 'ORD-0000-000';

/** Reference the backend returns once the order is submitted (shown in the success modal). */
// TODO(orval): use the reference from the create/update mutation response.
export const SUBMITTED_ORDER_REFERENCE = 'PO-2026-04821';

/** Pre-filled delivery date (ISO for the date input; design shows 28-02-2026). */
export const DEFAULT_DELIVERY_DATE = '2026-02-28';

// --- Product catalog ------------------------------------------------------
// TODO(orval): replace with useGetProducts() (filtered by the chosen supplier).
export interface CreateOrderProductOption {
  id: string;
  /** Full display name, e.g. "Premium Motor Spirit (PMS)". */
  name: string;
  /** Short label used in the order summary, e.g. "PMS". */
  shortLabel: string;
  /** Catalog code shown under the name, e.g. "PRD-PMS-001". */
  code: string;
  /** Price per unit in naira. */
  unitPrice: number;
  /** Singular unit name, e.g. "Litre". */
  unit: string;
  /** Short unit suffix shown on the quantity stepper, e.g. "L". */
  unitAbbrev: string;
  /** Minimum order quantity; also the stepper increment. */
  moq: number;
  /** Eligible for the gold-tier discount (shown as "Gold: 10% off"). */
  goldDiscount: boolean;
  available: boolean;
}

export const PRODUCT_CATALOG: CreateOrderProductOption[] = [
  {
    id: 'pms',
    name: 'Premium Motor Spirit (PMS)',
    shortLabel: 'PMS',
    code: 'PRD-PMS-001',
    unitPrice: 620,
    unit: 'Litre',
    unitAbbrev: 'L',
    moq: 100,
    goldDiscount: true,
    available: true,
  },
  {
    id: 'ago',
    name: 'Automotive Gas Oil (AGO)',
    shortLabel: 'AGO',
    code: 'PRD-AGO-003',
    unitPrice: 980,
    unit: 'Litre',
    unitAbbrev: 'L',
    moq: 100,
    goldDiscount: true,
    available: true,
  },
  {
    id: 'dpk',
    name: 'Dual Purpose Kerosene (DPK)',
    shortLabel: 'DPK',
    code: 'PRD-DPK-001',
    unitPrice: 940,
    unit: 'Litre',
    unitAbbrev: 'L',
    moq: 100,
    goldDiscount: false,
    available: true,
  },
];

/** Fuel types broken out as line rows in the order summary (PMS, AGO). */
export const SUMMARY_PRODUCT_IDS = ['pms', 'ago'] as const;

// --- Delivery methods -----------------------------------------------------
// TODO(orval): replace with useGetDeliveryMethods().
export interface CreateOrderDeliveryMethod {
  id: string;
  title: string;
  description: string;
  /** Fee in naira; 0 renders as "Free". */
  fee: number;
}

export const DELIVERY_METHODS: CreateOrderDeliveryMethod[] = [
  {
    id: 'supplier',
    title: 'Supplier Delivery',
    description: 'Goods delivered directly to your registered depot address within the agreed SLA.',
    fee: 0,
  },
  {
    id: 'pickup',
    title: 'Self Pick-Up',
    description: "Collect from supplier's dispatch center. Bring authorization letter and valid ID.",
    fee: 0,
  },
  {
    id: 'third-party',
    title: 'Third-Party Logistics',
    description: 'Arrange your own logistics partner. Supplier will load at their facility.',
    fee: 42000,
  },
];

export const DEFAULT_DELIVERY_METHOD_ID = 'supplier';

export const DELIVERY_NOTICE =
  "Delivery is guaranteed within 3-5 business days for Gold tier distributors. You'll receive real-time tracking once dispatched.";

// --- Delivery contact (from the distributor profile) ----------------------
// TODO(orval): replace with the authenticated distributor's profile/address.
export interface CreateOrderDeliveryContact {
  address: string;
  contactPerson: string;
  email: string;
}

export const DEFAULT_DELIVERY_CONTACT: CreateOrderDeliveryContact = {
  address: '15 Ikorodu Road, Lagos',
  contactPerson: 'Emeka Okafor',
  email: 'rainoil@gmail.com',
};

// --- Trading account ------------------------------------------------------
// TODO(orval): replace with useGetWalletBalance() (GET /wallets/read).
export const TRADING_ACCOUNT = {
  balance: 6400000,
  status: 'Active',
} as const;

export const SUCCESS_HUE = '#388E3C';

// --- Edit-order fixture ---------------------------------------------------
// TODO(orval): replace with useGetOrder(orderId) — the order being edited. The
// create flow starts blank; the edit flow seeds the form with this snapshot.
export interface EditOrderFixture {
  orderReference: string;
  supplierId: string;
  deliveryDate: string;
  lineItems: { productId: string; quantity: number }[];
  deliveryMethodId: string;
  contact: CreateOrderDeliveryContact;
}

export function getEditOrder(orderId: string): EditOrderFixture {
  return {
    // The route id stands in for the real order reference until the API lands.
    orderReference: orderId || 'ORD-6574-39F',
    supplierId: DEFAULT_SUPPLIER_ID,
    deliveryDate: DEFAULT_DELIVERY_DATE,
    lineItems: [
      { productId: 'pms', quantity: 5000 },
      { productId: 'ago', quantity: 2000 },
    ],
    deliveryMethodId: DEFAULT_DELIVERY_METHOD_ID,
    contact: DEFAULT_DELIVERY_CONTACT,
  };
}
